### ISSUE TITLE
No such file or directory: u/'accounts/XXX.json'

### ISSUE THREAD

**Issue by cstrachan88** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#102]
Not sure where this is going wrong. My account json file is not being created for some reason.

> C:\...\Pokemon-Go-Bot-Working-Hack-API>python pokebot.py -i 0 --cached
> 2016-07-24 20:49:42,157 [   pokebot] [ INFO] Your given location: XXX
> 2016-07-24 20:49:42,161 [   pokebot] [ INFO] lat/long/alt: XXX XXX 0.0
> 2016-07-24 20:49:42,164 [auth_google] [ INFO] Google login for: XXX
> 2016-07-24 20:49:42,884 [auth_google] [ INFO] Google Login successful.
> 2016-07-24 20:49:42,887 [    pgoapi] [ INFO] Starting RPC login sequence (app simulation)
> Traceback (most recent call last):
>   File "pokebot.py", line 99, in <module>
>     main()
>   File "pokebot.py", line 86, in main
>     if not api.login(config.auth_service, config.username, config.password, config.cached):
>   File "C:\...\Pokemon-Go-Bot-Working-Hack-API\pgoapi\pgoapi.py", line 350, in login
>     response = self.heartbeat()
>   File "C:\...\Pokemon-Go-Bot-Working-Hack-API\pgoapi\pgoapi.py", line 142, in heartbeat
>     with open("accounts/%s.json" % self.config['username'], "r") as f:
> IOError: [Errno 2] No such file or directory: u'accounts/XXX.json'

**Comment by cstrachan88** [comment]
Oh scratch that, I see what I did wrong. I added the changes from #91 so it's looking for the json file that hasn't been created yet
