### ISSUE TITLE
'long' not defined

### ISSUE THREAD

**Issue by rayzan91** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#11]
I'm trying to run the script for the first time using Python 3 on a Mac and I get the following:

Traceback (most recent call last):
File "pokebot.py", line 31, in 
from pgoapi import PGoApi
File "/Users/gonz/Desktop/PGo/PGoBotWorking/pgoapi/PGoApi.py", line 30, in 
from rpc_api import RpcApi
File "/Users/gonz/Desktop/PGo/PGoBotWorking/rpc_api.py", line 33, in 
from protobuf_to_dict import protobuf_to_dict
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/protobuf_to_dict.py", line 15, in 
FieldDescriptor.TYPE_INT64: long,
NameError: name 'long' is not defined

Can you please help me out?

**Comment by rayzan91** [comment]
I'm trying to run the script for the first time using Python 3 on a Mac and I get the following:

Traceback (most recent call last):
  File "pokebot.py", line 31, in <module>
    from pgoapi import PGoApi
  File "/Users/gonz/Desktop/PGo/PGoBotWorking/pgoapi/PGoApi.py", line 30, in <module>
    from rpc_api import RpcApi
  File "/Users/gonz/Desktop/PGo/PGoBotWorking/rpc_api.py", line 33, in <module>
    from protobuf_to_dict import protobuf_to_dict
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/protobuf_to_dict.py", line 15, in <module>
    FieldDescriptor.TYPE_INT64: long,
NameError: name 'long' is not defined


Can you please help me out?

**Comment by rayzan91** [comment]
I also tried using Python 2.7 but it doesn't go past

Traceback (most recent call last):
  File "pokebot.py", line 28, in <module>
    import requests
ImportError: No module named requests

**Comment by TomTheBotter** [comment]
See the following link: http://docs.python-requests.org/en/master/user/install/
