### ISSUE TITLE
OSX error

### ISSUE THREAD

**Issue by zhudan** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#112]
`Traceback (most recent call last):
  File "pokebot.py", line 99, in <module>
    main()
  File "pokebot.py", line 77, in main
    position = get_pos_by_name(config.location)
  File "pokebot.py", line 27, in get_pos_by_name
    loc = geolocator.geocode(location_name)
  File "/Library/Python/2.7/site-packages/geopy/geocoders/googlev3.py", line 217, in geocode
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/Library/Python/2.7/site-packages/geopy/geocoders/base.py", line 171, in _call_geocoder
    raise GeocoderServiceError(message)
geopy.exc.GeocoderServiceError: <urlopen error [Errno 65] No route to host>`

when use xx-net proxy, error :`Traceback (most recent call last):
  File "pokebot.py", line 99, in <module>
    main()
  File "pokebot.py", line 77, in main
    position = get_pos_by_name(config.location)
  File "pokebot.py", line 27, in get_pos_by_name
    loc = geolocator.geocode(location_name)
  File "/Library/Python/2.7/site-packages/geopy/geocoders/googlev3.py", line 217, in geocode
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/Library/Python/2.7/site-packages/geopy/geocoders/base.py", line 171, in _call_geocoder
    raise GeocoderServiceError(message)
geopy.exc.GeocoderServiceError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>`

can you help me ?

**Comment by Sytharix** [comment]
Does this happen when you run `pip install -r requirements.txt`?

**Comment by TomTheBotter** [comment]
API key verification failed; get a new one
