### ISSUE TITLE
JSON still not working

### ISSUE THREAD

**Issue by kairotox** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#12]
`Traceback (most recent call last):
  File "pokebot.py", line 194, in <module>
    main()
  File "pokebot.py", line 122, in main
    config = init_config()
  File "pokebot.py", line 83, in init_config
    load.update(json.load(data))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded`

`#log.info('Your given location: %s', loc.address.encode('utf-8'))
#log.info('lat/long/alt: %s %s %s', loc.latitude, loc.longitude, loc.altitude)
    return (34.008828, -118.497692, 0) # CHange this to ure long or lat or uncomment below stm if u have google geologcater api
    #return (loc.latitude, loc.longitude, loc.altitude)`

That's the right place in Pokebot.py to put the coords, right? the blue text in the "get_pos_by_name" section

Also, I'm running the terminal from this location:
![screen shot 2016-07-22 at 2 00 33 pm](https://cloud.githubusercontent.com/assets/20601026/17066357/b501af70-5014-11e6-941e-9aee501dcaa1.png)

**Comment by TomTheBotter** [comment]
Run under PGoBotWorking

**Comment by kairotox** [comment]
Same error: Traceback (most recent call last):
  File "pokebot.py", line 184, in <module>
    main()
  File "pokebot.py", line 113, in main
    config = init_config()
  File "pokebot.py", line 74, in init_config
    load.update(json.load(data))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by kairotox** [comment]
{"accounts" :
    [{
        "auth_service": "google",
        "username": "test@gmail.com",
        "password": "password",
        "location": "Irvine, CA"
    },
    {  "auth_service": "ptc",
        "username": “myuserhere”,
        "password": “mypwhere”,
        "location": "Irvine, CA"
    }
    ]

that's my config.

def get_pos_by_name(location_name):
    geolocator = GoogleV3()
    loc = geolocator.geocode(location_name)
    return (34.008747, -118.497628, 0.0) # INSERT YOUR LONGITUDE AND LATITUDE AND ALTITUDE HERE
    #return (loc.latitude, loc.longitude, loc.altitude)
that's the pos

**Comment by kairotox** [comment]
Did a bit of research, and found this: https://jsonformatter.curiousconcept.com/ so i ran my config through it, and I needed to swap out the double quotes that my text-editor put in there for the other ones in the file. ie “ was changed to "

**Comment by kairotox** [comment]
however, now i'm getting this error: Traceback (most recent call last):
  File "pokebot.py", line 184, in <module>
    main()
  File "pokebot.py", line 113, in main
    config = init_config()
  File "pokebot.py", line 74, in init_config
    load.update(json.load(data))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting object: line 13 column 5 (char 303)

**Comment by kairotox** [comment]
There was a } missing at the end of the config file. Got it, it's running now.
