### ISSUE TITLE
 No module named gpsoauth

### ISSUE THREAD

**Issue by silentsaintR** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#125]
silentsaint@silentsaintR ~/Masaüstü/Pokemon-Go-Bot-Working-Hack-API-master $ **sudo python pokebot.py -i 0 --cache**
Traceback (most recent call last):
  File "pokebot.py", line 15, in <module>
    from pgoapi import PGoApi
  File "/home/silentsaint/Masaüstü/Pokemon-Go-Bot-Working-Hack-API-master/pgoapi/__init__.py", line 18, in <module>
    from pgoapi.pgoapi import PGoApi
  File "/home/silentsaint/Masaüstü/Pokemon-Go-Bot-Working-Hack-API-master/pgoapi/pgoapi.py", line 13, in <module>
    from pgoapi.auth_google import AuthGoogle
  File "/home/silentsaint/Masaüstü/Pokemon-Go-Bot-Working-Hack-API-master/pgoapi/auth_google.py", line 28, in <module>
    from gpsoauth import perform_master_login, perform_oauth
ImportError: No module named gpsoauth

Any leads?

**Comment by TomTheBotter** [comment]
Import it manually
