### ISSUE TITLE
KeyError: 'accounts'

### ISSUE THREAD

**Issue by ra1kkonen** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#14]
Did everything according to the setup file, but when I try to run the script I get this:

Traceback (most recent call last):
  File "downloads/pgobotworking/pokebot.py", line 184, in <module>
    main()
  File "downloads/pgobotworking/pokebot.py", line 113, in main
    config = init_config()
  File "downloads/pgobotworking/pokebot.py", line 79, in init_config
    required=required("auth_service"))
  File "downloads/pgobotworking/pokebot.py", line 77, in <lambda>
    required = lambda x: not x in load['accounts'][0].keys()
KeyError: 'accounts'

I'm running OSX 10.11.5 and Python 2.7.12. What could be the error?

**Comment by TomTheBotter** [comment]
See latest update

**Comment by thatsmyface** [comment]
I have the latest update and am still getting the same error. Am I doing this correctly?
`C:\Users\ethan>C:\Python27\python.exe C:\Users\Ethan\Desktop\Pokemon-Go-Bot-Working-Hack-API-master\pokebot.py -i 0
Traceback (most recent call last):
  File "C:\Users\Ethan\Desktop\Pokemon-Go-Bot-Working-Hack-API-master\pokebot.py", line 99, in <module>
    main()
  File "C:\Users\Ethan\Desktop\Pokemon-Go-Bot-Working-Hack-API-master\pokebot.py", line 68, in main
    config = init_config()
  File "C:\Users\Ethan\Desktop\Pokemon-Go-Bot-Working-Hack-API-master\pokebot.py", line 43, in init_config
    required=required("auth_service"))
  File "C:\Users\Ethan\Desktop\Pokemon-Go-Bot-Working-Hack-API-master\pokebot.py", line 41, in <lambda>
    required = lambda x: not x in load['accounts'][0].keys()
KeyError: 'accounts'`

I am using a Google account. My config looks like this:
`{"accounts" :
    [{
        "auth_service": "google",
        "username": "USERNAME",
        "password": "PASSWORD",
        "location": "Portsmouth, NH",
        "USE_GOOGLE": true,
        "GMAPS_API_KEY": "APIKEY",
        "MIN_KEEP_IV" : 0,
        "KEEP_CP_OVER": 0,
        "STEP_SIZE": 100
    },
    {  "auth_service": "ptc",
        "username": "USERNAME",
        "password": "PASSWORD",
        "location": "Portsmouth, NH",
        "USE_GOOGLE": true,
        "GMAPS_API_KEY": "APIKEY",
        "MIN_KEEP_IV" : 0,
        "KEEP_CP_OVER": 0,
        "STEP_SIZE": 100
    }
    ]}
`
(I have the username, password, and APIkey filled in I just didn't show it in this post)

**Comment by TomTheBotter** [comment]
Did you try it with a PTC account?

**Comment by thatsmyface** [comment]
Yup :) it's working now!
