### ISSUE TITLE
error~~ how can i fix this??

### ISSUE THREAD

**Issue by weiliang717** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#149]
how can i fix this?
i just finish install the protobuf3 error,
and then when i run it, it still give me error, but different one~ 
please help~

C:\Users\Administrator>cd C:\Users\Administrator\Downloads\Pokemon-Go-Bot-Workin
g-Hack-API-master

C:\Users\Administrator\Downloads\Pokemon-Go-Bot-Working-Hack-API-master>C:\Pytho
n27\python.exe pokebot.py -i 0 --cache
Traceback (most recent call last):
  File "pokebot.py", line 99, in <module>
    main()
  File "pokebot.py", line 68, in main
    config = init_config()
  File "pokebot.py", line 39, in init_config
    load.update(json.load(data))
  File "C:\Python27\Lib\json\__init__.py", line 291, in load
    **kw)
  File "C:\Python27\Lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\Lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\Lib\json\decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 6 column 22 (char 156)

C:\Users\Administrator\Downloads\Pokemon-Go-Bot-Working-Hack-API-master>

**Comment by nesttle** [comment]
Try with the original PGOAPI (last updated): https://github.com/j-e-k/pgoapi
