### ISSUE TITLE
somethink went wrong

### ISSUE THREAD

**Issue by weirdohunt** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#150]
C:\Users\xxxxxx\Desktop\poke\hacks\Pokemon-Go-Bot-Working-Hack-API-master\Pokemon-Go-Bot-Working-Hack-API-master num 1>"C:\Python27\python.exe" pokebot.py -i 0
Traceback (most recent call last):
  File "pokebot.py", line 99, in <module>
    main()
  File "pokebot.py", line 68, in main
    config = init_config()
  File "pokebot.py", line 39, in init_config
    load.update(json.load(data))
  File "C:\Python27\lib\json\__init__.py", line 291, in load
    **kw)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 20 column 9 (char 635)

**Comment by nesttle** [comment]
Try with the original PGOAPI (last updated): https://github.com/j-e-k/pgoapi
