### ISSUE TITLE
ImportError: No module named protobuf_to_dict

### ISSUE THREAD

**Issue by CreativityJoker** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#17]
Traceback (most recent call last):
  File "pokebot.py", line 13, in <module>
    from pgoapi import PGoApi
  File "C:\Users\Butler\Downloads\Downloads\Pokemon-Go-Bot-Working-Hack-API-master\Pokemon-Go-Bot-Working-Hack-API-master\PGoBotWorking\pgoapi\__init__.py", line 1, in <module>
    from pgoapi      import *
  File "C:\Users\Butler\Downloads\Downloads\Pokemon-Go-Bot-Working-Hack-API-master\Pokemon-Go-Bot-Working-Hack-API-master\PGoBotWorking\pgoapi\pgoapi.py", line 10, in <module>
    from rpc_api import RpcApi
  File "C:\Users\Butler\Downloads\Downloads\Pokemon-Go-Bot-Working-Hack-API-master\Pokemon-Go-Bot-Working-Hack-API-master\PGoBotWorking\pgoapi\rpc_api.py", line 33, in <module>
    from protobuf_to_dict import protobuf_to_dict
ImportError: No module named protobuf_to_dict

**Comment by TomTheBotter** [comment]
I believe someone else posted the solution to this on reddit

**Comment by CreativityJoker** [comment]
Thanks. I figured out the error. Installing Microsoft Visual C++ Compiler for Python 2.7 solved it.
