### ISSUE TITLE
pip install -r requirements.txt

### ISSUE THREAD

**Issue by jryz** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#21]
Whenever I try to install the requirements I end up with "Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/yb/0gfvwv6x5hv1kxm9281klq9h0000gn/T/pip-build-VtRUpw/protobuf-to-dict/"

**Comment by DaveBobFred** [comment]
Install Microsoft Visual C++ Compiler for Python 2.7 then try again.

[https://www.microsoft.com/en-us/download/details.aspx?id=44266](url)

**Comment by jryz** [comment]
I forgot to add, I'm having this issue on mac

**Comment by TomTheBotter** [comment]
Are you still having this issue after installing the above link?

**Comment by drgnx** [comment]
I was having the same issue with this on OSX, but here's what I did to fix it:

Install Homebrew (http://brew.sh/), run `brew doctor`, and fix everything it tells you to fix. After that, install Homebrew's Python 2.7 with `brew install python`, and then go to the Bot directory and run `pip install -r requirements.txt`. It should install the required modules to Homebrew's Python directory instead of the default one. The default one won't let you make any changes to it without an administrator password, and I think that was the problem.

**Comment by TaylorZaneKirk** [comment]
Still having issues after downloading the C++ compiler for Python. Dumping my log:

```
Complete output from command python setup.py egg_info:
    using bundled proj4..
    Traceback (most recent call last):
      File "C:\Users\Taylor\Anaconda3\lib\site-packages\setuptools-17.1.1-py3.4.egg\setuptools\msvc9_support.py", line 52, in query_vcvarsall
      File "C:\Users\Taylor\Anaconda3\lib\distutils\msvc9compiler.py", line 259, in query_vcvarsall
        raise DistutilsPlatformError("Unable to find vcvarsall.bat")
    distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Taylor\AppData\Local\Temp\pip-build-u5vz8ijb\pyproj\setup.py", line 72, in <module>
        objects = cc.compile(['nad2bin.c', 'src/pj_malloc.c'])
      File "C:\Users\Taylor\Anaconda3\lib\distutils\msvc9compiler.py", line 460, in compile
        self.initialize()
      File "C:\Users\Taylor\Anaconda3\lib\distutils\msvc9compiler.py", line 371, in initialize
        vc_env = query_vcvarsall(VERSION, plat_spec)
      File "C:\Users\Taylor\Anaconda3\lib\site-packages\setuptools-17.1.1-py3.4.egg\setuptools\msvc9_support.py", line 62, in query_vcvarsall
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 10.0 is required (Unable to find vcvarsall.bat).

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1
```

**Comment by krishnaglick** [comment]
FWIW the C++ Compiler fixed this issue for me on Win7.

**Comment by nightguerreiro** [comment]
I fixed that problem downloading the vc for python: https://download.microsoft.com/download/7/9/6/796EF2E4-801B-4FC4-AB28-B59FBF6D907B/VCForPython27.msi
