### ISSUE TITLE
No module auth_ptc

### ISSUE THREAD

**Issue by Spurlex** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#29]
```
Traceback (most recent call last):
  File "pokebot.py", line 15, in <module>
    from pgoapi import PGoApi
  File "/Users/Michael/Pokemon-Go-Bot-Working-Hack-API/pgoapi/__init__.py", line 18, in <module>
    from pgoapi.pgoapi import PGoApi
  File "/Users/Michael/Pokemon-Go-Bot-Working-Hack-API/pgoapi/pgoapi.py", line 12, in <module>
    from pgoapi.auth_ptc import AuthPtc
ImportError: No module named auth_ptc
```

**Comment by TomTheBotter** [comment]
So sorry! I don't use github often, and some files were not being pushed.

**Comment by TomTheBotter** [comment]
It should work now
