### ISSUE TITLE
no JSON object could be detected

### ISSUE THREAD

**Issue by RovingSpirit** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#30]
After running python pokebot -i 1 i get the error

Traceback (most recent call last):
  File "pokebot.py", line 99, in <module>
    main()
  File "pokebot.py", line 68, in main
    config = init_config()
  File "pokebot.py", line 39, in init_config
    load.update(json.load(data))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Deans-Air:bot2 Dean$ python pokebot.py -i 1

**Comment by TomTheBotter** [comment]
https://github.com/TomTheBotter/Pokemon-Go-Bot-Working-Hack-API/issues/12 See that issue
