### ISSUE TITLE
Trying to run it on Mac, get this ERROR. No JSON object could be decoded. Help appreciated!

### ISSUE THREAD

**Issue by moeops** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#42]
Traceback (most recent call last):
  File "pokebot.py", line 99, in <module>
    main()
  File "pokebot.py", line 68, in main
    config = init_config()
  File "pokebot.py", line 39, in init_config
    load.update(json.load(data))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by moeops** [comment]
Thank you in advance!

I installed homebrew and protobuf, I'm running Python 2.7.X

**Comment by jolbol1** [comment]
Hey, I had a similar problem and read elsewhere that if you look in your config.json there are two types of ", Make sure all of the " in your config are the parallel kind and not curved.

**Comment by moeops** [comment]
@jolbol1 This worked, thanks.

**Comment by leveled** [comment]
This problem actually came up for me several hours after running the bot and subsequently restarting it. All of the quotation marks in the config.json file are parallel.
