### ISSUE TITLE
Bot wont start (Ubuntu)

### ISSUE THREAD

**Issue by aeeh** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#47]
```
python2.7 pokebot.py -i 0
Traceback (most recent call last):
  File "pokebot.py", line 12, in <module>
    import requests
  File "/home/sebastian/.local/lib/python2.7/site-packages/requests/__init__.py", line 61, in <module>
    from .packages.urllib3.exceptions import DependencyWarning
  File "/home/sebastian/.local/lib/python2.7/site-packages/requests/packages/__init__.py", line 29, in <module>
    import urllib3
ImportError: No module named urllib3
```

Whats wront here ?

**Comment by VNadygin** [comment]
same problem: 
Traceback (most recent call last):
  File "pokebot.py", line 12, in <module>
    import requests
  File "/Library/Python/2.7/site-packages/requests/__init__.py", line 61, in <module>
    from .packages.urllib3.exceptions import DependencyWarning
  File "/Library/Python/2.7/site-packages/requests/packages/__init__.py", line 29, in <module>
    import urllib3
ImportError: No module named urllib3

**Comment by aeeh** [comment]
How can we solve the problem?

**Comment by Sytharix** [comment]
Try running `hash -r python` or logging out and logging back in.

**Comment by esfomeado** [comment]
sudo pip install urllib3 --upgrade
