### ISSUE TITLE
Issues with installing requirements on OS X

### ISSUE THREAD

**Issue by themanticors** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#48]
Using a MacBook with latest OS X. Installed the latest python package 2.7.12 and installed pip. Getting the errors below with regular install and sudo install command.

```
********-MacBook-Pro:pokemongo *****************$ pip install -r requirements.txt
Collecting geopy==1.11.0 (from -r requirements.txt (line 1))
  Using cached geopy-1.11.0-py2.py3-none-any.whl
Collecting protobuf>=3.0.0a3 (from -r requirements.txt (line 2))
  Using cached protobuf-3.0.0b4.tar.gz
Collecting requests==2.10.0 (from -r requirements.txt (line 3))
  Using cached requests-2.10.0-py2.py3-none-any.whl
Collecting s2sphere==0.2.4 (from -r requirements.txt (line 4))
  Using cached s2sphere-0.2.4-py2.py3-none-any.whl
Collecting gpsoauth==0.3.0 (from -r requirements.txt (line 5))
  Using cached gpsoauth-0.3.0.tar.gz
Collecting pyproj==1.9.5.1 (from -r requirements.txt (line 6))
  Using cached pyproj-1.9.5.1.tar.gz
Collecting python-gmaps==0.3.1 (from -r requirements.txt (line 7))
  Using cached python_gmaps-0.3.1-py2.py3-none-any.whl
Collecting Flask==0.11.1 (from -r requirements.txt (line 8))
  Using cached Flask-0.11.1-py2.py3-none-any.whl
Collecting Jinja2==2.7.1 (from -r requirements.txt (line 9))
  Using cached Jinja2-2.7.1.tar.gz
Collecting six>=1.9 (from protobuf>=3.0.0a3->-r requirements.txt (line 2))
  Using cached six-1.10.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): setuptools in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from protobuf>=3.0.0a3->-r requirements.txt (line 2))
Collecting future (from s2sphere==0.2.4->-r requirements.txt (line 4))
  Using cached future-0.15.2.tar.gz
Collecting pycryptodomex>=3.0 (from gpsoauth==0.3.0->-r requirements.txt (line 5))
  Using cached pycryptodomex-3.4.2.tar.gz
Requirement already satisfied (use --upgrade to upgrade): pytz in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from python-gmaps==0.3.1->-r requirements.txt (line 7))
Collecting itsdangerous>=0.21 (from Flask==0.11.1->-r requirements.txt (line 8))
  Using cached itsdangerous-0.24.tar.gz
Collecting Werkzeug>=0.7 (from Flask==0.11.1->-r requirements.txt (line 8))
  Using cached Werkzeug-0.11.10-py2.py3-none-any.whl
Collecting click>=2.0 (from Flask==0.11.1->-r requirements.txt (line 8))
  Using cached click-6.6.tar.gz
Collecting markupsafe (from Jinja2==2.7.1->-r requirements.txt (line 9))
  Using cached MarkupSafe-0.23.tar.gz
Installing collected packages: geopy, six, protobuf, requests, future, s2sphere, pycryptodomex, gpsoauth, pyproj, python-gmaps, itsdangerous, Werkzeug, markupsafe, Jinja2, click, Flask
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_install.py", line 831, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_install.py", line 1032, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/wheel.py", line 346, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/wheel.py", line 317, in clobber
    ensure_dir(destdir)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/geopy'
```
```
********-MacBook-Pro:pokemongo *****************$ sudo pip install -r requirements.txt
Password:
The directory '/Users/*****/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/*****/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting geopy==1.11.0 (from -r requirements.txt (line 1))
  Downloading geopy-1.11.0-py2.py3-none-any.whl (66kB)
    100% |████████████████████████████████| 71kB 490kB/s 
Collecting protobuf>=3.0.0a3 (from -r requirements.txt (line 2))
  Downloading protobuf-3.0.0b4.tar.gz (210kB)
    100% |████████████████████████████████| 215kB 1.0MB/s 
Collecting requests==2.10.0 (from -r requirements.txt (line 3))
  Downloading requests-2.10.0-py2.py3-none-any.whl (506kB)
    100% |████████████████████████████████| 512kB 971kB/s 
Collecting s2sphere==0.2.4 (from -r requirements.txt (line 4))
  Downloading s2sphere-0.2.4-py2.py3-none-any.whl
Collecting gpsoauth==0.3.0 (from -r requirements.txt (line 5))
  Downloading gpsoauth-0.3.0.tar.gz
Collecting pyproj==1.9.5.1 (from -r requirements.txt (line 6))
  Downloading pyproj-1.9.5.1.tar.gz (4.4MB)
    100% |████████████████████████████████| 4.4MB 271kB/s 
Collecting python-gmaps==0.3.1 (from -r requirements.txt (line 7))
  Downloading python_gmaps-0.3.1-py2.py3-none-any.whl
Collecting Flask==0.11.1 (from -r requirements.txt (line 8))
  Downloading Flask-0.11.1-py2.py3-none-any.whl (80kB)
    100% |████████████████████████████████| 81kB 5.0MB/s 
Collecting Jinja2==2.7.1 (from -r requirements.txt (line 9))
  Downloading Jinja2-2.7.1.tar.gz (377kB)
    100% |████████████████████████████████| 378kB 2.0MB/s 
Collecting six>=1.9 (from protobuf>=3.0.0a3->-r requirements.txt (line 2))
  Downloading six-1.10.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): setuptools in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from protobuf>=3.0.0a3->-r requirements.txt (line 2))
Collecting future (from s2sphere==0.2.4->-r requirements.txt (line 4))
  Downloading future-0.15.2.tar.gz (1.6MB)
    100% |████████████████████████████████| 1.6MB 499kB/s 
Collecting pycryptodomex>=3.0 (from gpsoauth==0.3.0->-r requirements.txt (line 5))
  Downloading pycryptodomex-3.4.2.tar.gz (6.5MB)
    100% |████████████████████████████████| 6.5MB 178kB/s 
Requirement already satisfied (use --upgrade to upgrade): pytz in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from python-gmaps==0.3.1->-r requirements.txt (line 7))
Collecting itsdangerous>=0.21 (from Flask==0.11.1->-r requirements.txt (line 8))
  Downloading itsdangerous-0.24.tar.gz (46kB)
    100% |████████████████████████████████| 51kB 4.0MB/s 
Collecting Werkzeug>=0.7 (from Flask==0.11.1->-r requirements.txt (line 8))
  Downloading Werkzeug-0.11.10-py2.py3-none-any.whl (306kB)
    100% |████████████████████████████████| 307kB 3.4MB/s 
Collecting click>=2.0 (from Flask==0.11.1->-r requirements.txt (line 8))
  Downloading click-6.6.tar.gz (283kB)
    100% |████████████████████████████████| 286kB 981kB/s 
Collecting markupsafe (from Jinja2==2.7.1->-r requirements.txt (line 9))
  Downloading MarkupSafe-0.23.tar.gz
Installing collected packages: geopy, six, protobuf, requests, future, s2sphere, pycryptodomex, gpsoauth, pyproj, python-gmaps, itsdangerous, Werkzeug, markupsafe, Jinja2, click, Flask
  Found existing installation: six 1.4.1
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_set.py", line 736, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_install.py", line 742, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/tmp/pip-9nzE8W-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'
```

Before this particular error got a message on my first try to install the requirements to install the Xcode dev tools which I did, with the error message shown as below.

```
********-MacBook-Pro:pokemongo *****************$ pip install -r requirements.txt
Collecting geopy==1.11.0 (from -r requirements.txt (line 1))
  Using cached geopy-1.11.0-py2.py3-none-any.whl
Collecting protobuf>=3.0.0a3 (from -r requirements.txt (line 2))
  Using cached protobuf-3.0.0b4.tar.gz
Collecting requests==2.10.0 (from -r requirements.txt (line 3))
  Using cached requests-2.10.0-py2.py3-none-any.whl
Collecting s2sphere==0.2.4 (from -r requirements.txt (line 4))
  Using cached s2sphere-0.2.4-py2.py3-none-any.whl
Collecting gpsoauth==0.3.0 (from -r requirements.txt (line 5))
  Using cached gpsoauth-0.3.0.tar.gz
Collecting pyproj==1.9.5.1 (from -r requirements.txt (line 6))
  Using cached pyproj-1.9.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    xcode-select: note: no developer tools were found at '/Applications/Xcode.app', requesting install. Choose an option in the dialog to download the command line developer tools.
    using bundled proj4..
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/9h/t19zr6b106987ckyt35clrnc0000gn/T/pip-build-zh11BB/pyproj/setup.py", line 72, in <module>
        objects = cc.compile(['nad2bin.c', 'src/pj_malloc.c'])
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/ccompiler.py", line 574, in compile
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/unixccompiler.py", line 122, in _compile
        raise CompileError, msg
    distutils.errors.CompileError: command 'cc' failed with exit status 1
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/9h/t19zr6b106987ckyt35clrnc0000gn/T/pip-build-zh11BB/pyproj/
```

**Comment by drgnx** [comment]
Same problem here. Tried running it as root too, no luck.

**Comment by BAMitUp** [comment]
I got around this by having pip skip the installation of six (because apparently it's already installed by Apple on OS X El Capitan but in a protected directory -- hence the error)

`pip install -r requirements.txt --ignore-install six`

or if you have permissions issues with that:

`sudo pip install -r requirements.txt --ignore-install six`
