### ISSUE TITLE
Need help running it for the first time. These two errors come up.

### ISSUE THREAD

**Issue by hdubb** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#49]
C:\Users\X\Desktop\Pokemon-Go-Bot-Working-Hack-API-master>"C:\Python27\python.exe" pokebot.py -i 1 --cache
Traceback (most recent call last):
  File "pokebot.py", line 15, in <module>
    from pgoapi import PGoApi
  File "C:\Users\Happy\Desktop\Pokemon-Go-Bot-Working-Hack-API-master\pgoapi\__init__.py", line 16, in <module>
    raise PleaseInstallProtobufVersion3()
pgoapi.exceptions.PleaseInstallProtobufVersion3

**Comment by MRokas** [comment]
did you do `pip install --upgrade -r requirements.txt`?

**Comment by hdubb** [comment]
C:\Users\X\Desktop\Pokemon Go Bots\Pokemon-Go-Bot-Working-Hack-API-master>"C:\Python27\Scripts\pip2.7.exe" --upgrade -r requirements.txt

Like this right?

**Comment by MRokas** [comment]
Yes

**Comment by hdubb** [comment]
Yeah I did that. It is still showing the same errors.

**Comment by MRokas** [comment]
Hm, that's weird. I can only replicate this bug if I use python2.6 (exact same error). Could you run `C:\Python27\python.exe" --version`, just to make sure? I dont get to touch windows that much, so cant test it :/

**Comment by enokisoju** [comment]
Im on Windows 10 64B and get the same error as well, my version is 2.7 with Pip installed using the exact command line.

**Comment by MRokas** [comment]
Do you guys get any error in pip install?

**Comment by hdubb** [comment]
no, when I did pip install, nothing would show up. It would just load for 5
seconds, then, the default line would show up again.

**Comment by enokisoju** [comment]
https://github.com/google/protobuf/releases/download/v3.0.0-beta-4/protobuf-python-3.0.0-beta-4.zip

Download this. Unpack it, go into the setup folder and launch python setup.py install using Python.

Command line : python setup.py install

This should install Protobuf3 and you should be able to launch the Bot.

**Comment by hdubb** [comment]
This is the location where I should run it
right: "C:\Users\X\Desktop\protobuf-3.0.0-beta-4\python\setup.py"

and I run this command there: "C:\Python27\python.exe" setup.py install

I get this:

C:\Users\X\Desktop\protobuf-3.0.0-beta-4\python>"C:\Python27\python.exe"
setup.py install
running install
running bdist_egg
running egg_info
creating protobuf.egg-info
writing requirements to protobuf.egg-info\requires.txt
writing protobuf.egg-info\PKG-INFO
writing namespace_packages to protobuf.egg-info\namespace_packages.txt
writing top-level names to protobuf.egg-info\top_level.txt
writing dependency_links to protobuf.egg-info\dependency_links.txt
writing manifest file 'protobuf.egg-info\SOURCES.txt'
reading manifest file 'protobuf.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files found matching
'google\protobuf\internal\*_pb2.py'
warning: no previously-included files found matching
'google\protobuf\internal\*.proto'
warning: no previously-included files matching '*_test.py' found under
directory 'google'
warning: no previously-included files matching '*_test.proto' found under
directory 'google'
warning: no previously-included files matching 'unittest*_pb2.py' found
under directory 'google'
warning: no previously-included files matching '*.dll' found anywhere in
distribution
warning: no previously-included files matching '*.pyc' found anywhere in
distribution
warning: no previously-included files matching '*.pyo' found anywhere in
distribution
warning: no previously-included files matching '*.so' found anywhere in
distribution
writing manifest file 'protobuf.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
Generating google/protobuf/descriptor_pb2.py...
protoc is not installed nor found in ../src.  Please compile it or install
the binary package.
