### ISSUE TITLE
Cant figure it out. ImportError: No module named gmaps.directions?

### ISSUE THREAD

**Issue by hdubb** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#55]
C:\Users\Happy\Desktop\Pokemon Go Bots\Pokemon-Go-Bot-Working-Hack-API-master>"C:\Python27\python.exe" pokebot.py -i 1 --cache
Traceback (most recent call last):
  File "pokebot.py", line 15, in <module>
    from pgoapi import PGoApi
  File "C:\Users\Happy\Desktop\Pokemon Go Bots\Pokemon-Go-Bot-Working-Hack-API-master\pgoapi\__init__.py", line 18, in <module>
    from pgoapi.pgoapi import PGoApi
  File "C:\Users\Happy\Desktop\Pokemon Go Bots\Pokemon-Go-Bot-Working-Hack-API-master\pgoapi\pgoapi.py", line 22, in <module>
    from pgoapi.location import *
  File "C:\Users\Happy\Desktop\Pokemon Go Bots\Pokemon-Go-Bot-Working-Hack-API-master\pgoapi\location.py", line 5, in <module>
    from gmaps.directions import *
ImportError: No module named gmaps.directions

**Comment by krishabang** [comment]
Same issue here.
