### ISSUE TITLE
Problem with new version

### ISSUE THREAD

**Issue by reeplan** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#7]
`
pip install -r requirements.txt 
Requirement already satisfied (use --upgrade to upgrade): geopy==1.11.0 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 1))

Requirement already satisfied (use --upgrade to upgrade): protobuf==3.0.0b3 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 2))

Requirement already satisfied (use --upgrade to upgrade): requests==2.10.0 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 3))

Requirement already satisfied (use --upgrade to upgrade): s2sphere==0.2.4 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 4))

Requirement already satisfied (use --upgrade to upgrade): gpsoauth==0.3.0 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 5))

Requirement already satisfied (use --upgrade to upgrade): protobuf-to-dict==0.1.0 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 6))

Requirement already satisfied (use --upgrade to upgrade): pyproj==1.9.5.1 in /usr/lib64/python2.7/site-packages (from -r requirements.txt (line 7))

Requirement already satisfied (use --upgrade to upgrade): python-gmaps==0.3.1 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 8))

Requirement already satisfied (use --upgrade to upgrade): six>=1.9 in /usr/lib/python2.7/site-packages (from protobuf==3.0.0b3->-r requirements.txt (line 2))

Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python2.7/site-packages (from protobuf==3.0.0b3->-r requirements.txt (line 2))

Requirement already satisfied (use --upgrade to upgrade): future in /usr/lib/python2.7/site-packages (from s2sphere==0.2.4->-r requirements.txt (line 4))

Requirement already satisfied (use --upgrade to upgrade): pycryptodomex>=3.0 in /usr/lib64/python2.7/site-packages (from gpsoauth==0.3.0->-r requirements.txt (line 5))

Requirement already satisfied (use --upgrade to upgrade): pytz in /usr/lib/python2.7/site-packages (from python-gmaps==0.3.1->-r requirements.txt (line 8))
`
But
`python pokebot.py -i 0
Traceback (most recent call last):
  File "pokebot.py", line 31, in <module>
    from pgoapi import PGoApi
  File "/home/sup/pok/Pokemon-Go-Bot-Working-Hack-API-master/PGoWorkingBot/pgoapi/__init__.py", line 1, in <module>
    from pgoapi      import *
  File "/home/sup/pok/Pokemon-Go-Bot-Working-Hack-API-master/PGoWorkingBot/pgoapi/pgoapi.py", line 35, in <module>
    from auth_google import AuthGoogle
  File "/home/sup/pok/Pokemon-Go-Bot-Working-Hack-API-master/PGoWorkingBot/pgoapi/auth_google.py", line 29, in <module>
    from gpsoauth import perform_master_login, perform_oauth
  File "/usr/lib/python2.7/site-packages/gpsoauth/__init__.py", line 4, in <module>
    from . import google
  File "/usr/lib/python2.7/site-packages/gpsoauth/google.py", line 4, in <module>
    from Cryptodome.PublicKey import RSA
  File "/usr/lib64/python2.7/site-packages/Cryptodome/PublicKey/RSA.py", line 83, in <module>
    from Cryptodome.Math.Numbers import Integer
  File "/usr/lib64/python2.7/site-packages/Cryptodome/Math/Numbers.py", line 42, in <module>
    from Cryptodome.Math._Numbers_gmp import Integer
  File "/usr/lib64/python2.7/site-packages/Cryptodome/Math/_Numbers_gmp.py", line 198, in <module>
    class Integer(object):
  File "/usr/lib64/python2.7/site-packages/Cryptodome/Math/_Numbers_gmp.py", line 202, in Integer
    _gmp.mpz_init_set_ui(_zero_mpz_p, c_ulong(0))
TypeError: initializer for ctype 'MPZ' must be a list or tuple or dict or struct-cdata, not cdata 'MPZ *'
`

**Comment by TomTheBotter** [comment]
Try the latest update
