### ISSUE TITLE
No module named requests

### ISSUE THREAD

**Issue by enokisoju** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#70]
I'm getting:

Traceback (most recent call last):
  File "C:\Users\xxxx\Desktop\Pokemon-Go-Bot-Working-API-master\pokebot.py", line 12, in <module>
     import requests
ImportError: No module named requests

_______________________
Any help would be greatly appreciated and thanks in advance.

**Comment by Rushleader** [comment]
There should be an error code beneath it. Thats the indicator of what you should do.

**Comment by enokisoju** [comment]
If it helps im running the command through Command Prompt (windows 64). I see nothing like that. The run command im using is "pokebot.py -i 0 --cache" without the quotes and the other is without --cache

**Comment by enokisoju** [comment]
Traceback (most recent call last):
  File "C:\Users\xxxx\Desktop\Pokemon-Go-Bot-Working-API-master\pokebot.py", line 12, in <module>
    import requests
ImportError: No module named requests

**Comment by krishabang** [comment]
Do "pip install requests"

**Comment by enokisoju** [comment]
Says 'pip' is not recognized as an internl or external command, operable program or batch file.

But I installed pip and wheel through the windowed python program and it looked as if it was successful. Here's the output below.

Installing collected packages: pip, setuptools, wheel
Successfully installed pip-8.1.2 setuptools-25.0.0 wheel-0.29.0

Warning (from warnings module):
  File "c:\users\xxxx\appdata\local\temp\tmpp4otzy\pip.zip\pip\_vendor\requests\packages\urllib3\util\ssl_.py", line 122
InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.

Traceback (most recent call last):
  File "C:\Users\xxxx\Downloads\get-pip (1).py", line 19177, in <module>
    main()
  File "C:\Users\xxxx\Downloads\get-pip (1).py", line 194, in main
    bootstrap(tmpdir=tmpdir)
  File "C:\Users\xxxx\Downloads\get-pip (1).py", line 172, in bootstrap
    sys.exit(pip.main(["install", "--upgrade"] + args))

**Comment by enokisoju** [comment]
Python27 also if that helps

**Comment by enokisoju** [comment]
python -m pip install -U pip (Just ran this as well and it said Requirement already up-to-date: pip in c:\python27\lib\site-packages

**Comment by enokisoju** [comment]
Now I'm getting this output : 


Traceback (most recent call last):
  File "C:\Users\xxxx\Desktop\Pokemon-Go-Bot-Working-API-master\pokebot.py", line 15, in <module>
    from pgoapi import PGoApi
  File "C:\Users\xxxx\Desktop\Pokemon-Go-Bot-Working-API-master\pgoapi\__init__.py", line 16, in <module>
    raise PleaseInstallProtobufVersion3()
PleaseInstallProtobufVersion3

**Comment by enokisoju** [comment]
Installing Microsoft Visual C++ Compiler for Python 2.7 and trying again. Keep you updated.

**Comment by Rushleader** [comment]
Add python27/Scripts to PATH, should help aswell
that way pip command should be able to run

**Comment by enokisoju** [comment]
![paths](https://cloud.githubusercontent.com/assets/20628259/17085982/26b24e0e-51b4-11e6-8c23-d6ce01418f7d.jpg)

This is how I have them listed in there. Ran the command again and also returned this: 

Traceback (most recent call last):
  File "C:\Users\xxxx\Desktop\Pokemon-Go-Bot-Working-API-master\pokebot.py", line 15, in <module>
    from pgoapi import PGoApi
  File "C:\Users\xxxx\Desktop\Pokemon-Go-Bot-Working-API-master\pgoapi\__init__.py", line 16, in <module>
    raise PleaseInstallProtobufVersion3()
PleaseInstallProtobufVersion3

**Comment by NowNewStart** [comment]
https://github.com/google/protobuf/releases/download/v3.0.0-beta-4/protobuf-python-3.0.0-beta-4.zip

Download this. Unpack it, go into the setup folder and launch setup.py using Python.

This should install Protobuf3 and you should be able to launch the Bot.

**Comment by enokisoju** [comment]
Traceback (most recent call last):
  File "C:\Users\xxxx\Desktop\protobuf-3.0.0-beta-3\python\setup.py", line 249, in <module>
    ext_modules=ext_module_list,
  File "C:\Python27\lib\distutils\core.py", line 140, in setup
    raise SystemExit, gen_usage(dist.script_name) + "\nerror: %s" % msg
SystemExit: usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied

**Comment by NowNewStart** [comment]
Whoops. Run `python setup.py install` , this should work.

**Comment by enokisoju** [comment]
Lol now I have this:


Traceback (most recent call last):
  File "C:\Users\xxxx\Desktop\Pokemon-Go-Bot-Working-API-master\pokebot.py", line 15, in <module>
    from pgoapi import PGoApi
  File "C:\Users\xxxx\Desktop\Pokemon-Go-Bot-Working-API-master\pgoapi\__init__.py", line 18, in <module>
    from pgoapi.pgoapi import PGoApi
  File "C:\Users\enoki\Desktop\Pokemon-Go-Bot-Working-API-master\pgoapi\pgoapi.py", line 13, in <module>
    from pgoapi.auth_google import AuthGoogle
  File "C:\Users\xxxx\Desktop\Pokemon-Go-Bot-Working-API-master\pgoapi\auth_google.py", line 28, in <module>
    from gpsoauth import perform_master_login, perform_oauth
ImportError: No module named gpsoauth

**Comment by NowNewStart** [comment]
`pip install gpsoauth`

**Comment by enokisoju** [comment]
Had a few other errors and put two and two together and used the pip install to get past those, Now I'm stuck on directions.


Traceback (most recent call last):
  File "C:\Users\xxxx\Desktop\Pokemon-Go-Bot-Working-API-master\pokebot.py", line 15, in <module>
    from pgoapi import PGoApi
  File "C:\Users\xxxx\Desktop\Pokemon-Go-Bot-Working-API-master\pgoapi\__init__.py", line 18, in <module>
    from pgoapi.pgoapi import PGoApi
  File "C:\Users\xxxx\Desktop\Pokemon-Go-Bot-Working-API-master\pgoapi\pgoapi.py", line 22, in <module>
    from pgoapi.location import *
  File "C:\Users\xxxx\Desktop\Pokemon-Go-Bot-Working-API-master\pgoapi\location.py", line 5, in <module>
    from gmaps.directions import *
ImportError: No module named directions

**Comment by NowNewStart** [comment]
Did you try pip install on directions? :D

**Comment by enokisoju** [comment]
indeed

**Comment by NowNewStart** [comment]
Ah alright. Try `pip install -U googlemaps`

**Comment by enokisoju** [comment]
same

**Comment by NowNewStart** [comment]
Then just run `pip install -r requirements.txt` again and hope that this magically fixes it now.

Other than that, I really don't know anymore

**Comment by enokisoju** [comment]
i just did this pip install python-gmaps and it worked but it need s2sphere now lol

**Comment by NowNewStart** [comment]
Run the command I just posted

**Comment by enokisoju** [comment]
Nothing popped up after it, but now when ran it says i need pyproj module... Feels like im having to install every single module as it runs through them. and my analytical sense to try pip install pyproj didn't work. Eh.

**Comment by NowNewStart** [comment]
Thats what the command is actually for, every module is in the requirements.txt and I thought you have ran that already, but you didn't.

Alright the pyproj thing. I had that too, and found a way to fix it pretty quickly.
http://www.lfd.uci.edu/~gohlke/pythonlibs/#pyproj

Download the "pyproj-1.9.5.1-cp27-cp27m-win32.whl" and install it with `pip install pyproj-1.9.5.1-cp27-cp27m-win32.whl`

**Comment by enokisoju** [comment]
usage: pokebot.py [-h] [-a AUTH_SERVICE] -i CONFIG_INDEX [-u USERNAME]
                  [-p PASSWORD] [-l LOCATION] [-d] [-c] [-t]
pokebot.py: error: argument -i/--config_index is required

Traceback (most recent call last):
  File "C:\Users\xxxx\Desktop\Pokemon-Go-Bot-Working-API-master\pokebot.py", line 99, in <module>
    main()
  File "C:\Users\xxxx\Desktop\Pokemon-Go-Bot-Working-API-master\pokebot.py", line 68, in main
    config = init_config()
  File "C:\Users\xxxx\Desktop\Pokemon-Go-Bot-Working-API-master\pokebot.py", line 52, in init_config
    config = parser.parse_args()
  File "C:\Python27\lib\argparse.py", line 1656, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "C:\Python27\lib\argparse.py", line 1688, in parse_known_args
    return self._parse_known_args(args, namespace)
  File "C:\Python27\lib\argparse.py", line 1908, in _parse_known_args
    self.error(_('argument %s is required') % name)
  File "C:\Python27\lib\argparse.py", line 2311, in error
    self.exit(2, _('%s: error: %s\n') % (self.prog, message))
  File "C:\Python27\lib\argparse.py", line 2299, in exit
    _sys.exit(status)
SystemExit: 2

**Comment by NowNewStart** [comment]
We are almost done.

Configure yourself in the config.json file. Then launch the bot with `pokebot.py -i 0`

**Comment by enokisoju** [comment]
it still is, was one of the first things i did. or did notepad mess it up?

**Comment by NowNewStart** [comment]
Alright, then just do `python pokebot.py -i 0` 


The `-i 0` is the important thing, it's using the first configured account from the config.json

**Comment by enokisoju** [comment]
![error](https://cloud.githubusercontent.com/assets/20628259/17086682/928e9224-51c6-11e6-870e-620b02cabc70.jpg)

**Comment by NowNewStart** [comment]
There seems to be something wrong with either your login credentials or Google is fucking up. Otherwhise idk

**Comment by enokisoju** [comment]
so the SSL stuff is not the problem. Okay. Thank you so very much for 'all' the time and effort and help you provided. I'll keep trying then.
