### ISSUE TITLE
Can’t install (Mac OS)

### ISSUE THREAD

**Issue by rbnschlz** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#76]
Can anybody decipher what’s going wrong:

```
Collecting geopy==1.11.0 (from -r requirements.txt (line 1))
  Using cached geopy-1.11.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): protobuf>=3.0.0a3 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): requests==2.10.0 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from -r requirements.txt (line 3))
Collecting s2sphere==0.2.4 (from -r requirements.txt (line 4))
  Using cached s2sphere-0.2.4-py2.py3-none-any.whl
Collecting gpsoauth==0.3.0 (from -r requirements.txt (line 5))
Collecting pyproj==1.9.5.1 (from -r requirements.txt (line 6))
  Using cached pyproj-1.9.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    gcc-4.2 not found, using clang instead
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    using bundled proj4..
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/k6/9l0b1rtx1ss1ct1m_wvpxvsr0000gn/T/pip-build-cPAdSs/pyproj/setup.py", line 72, in <module>
        objects = cc.compile(['nad2bin.c', 'src/pj_malloc.c'])
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/ccompiler.py", line 572, in compile
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/unixccompiler.py", line 180, in _compile
        raise CompileError, msg
    distutils.errors.CompileError: command 'clang' failed with exit status 1
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/k6/9l0b1rtx1ss1ct1m_wvpxvsr0000gn/T/pip-build-cPAdSs/pyproj/
```

Much appreciated!

**Comment by Jay1** [comment]
This is related to pip, which is a mess most of time. I had the exact same problem when I installed it on Windows 10, turns out it was missing a very particular compiler from microsoft for python. 

This page [here](http://stackoverflow.com/questions/17886647/cant-install-via-pip-because-of-egg-info-error) is full of information about your problem. Good luck!

**Comment by Jay1** [comment]
(oh btw, if I was you, I would focus on "command 'clang' failed with exit status 1" ,  you're missing some compiler file, it could be vcvarsall)

**Comment by rbnschlz** [comment]
Thanks, solved it.
