### ISSUE TITLE
Windows Compile Error

### ISSUE THREAD

**Issue by AaronClover** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#77]
Requirement already satisfied (use --upgrade to upgrade): geopy==1.11.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 1))
Collecting protobuf>=3.0.0a3 (from -r requirements.txt (line 2))
  Using cached protobuf-3.0.0b4.tar.gz
Requirement already satisfied (use --upgrade to upgrade): requests==2.10.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): s2sphere==0.2.4 in c:\python27\lib\site-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): gpsoauth==0.3.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 5))
Collecting pyproj==1.9.5.1 (from -r requirements.txt (line 6))
  Using cached pyproj-1.9.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    using bundled proj4..
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\username\appdata\local\temp\pip-build-gsn2z7\pyproj\setup.py", line 72, in <module>
        objects = cc.compile(['nad2bin.c', 'src/pj_malloc.c'])
      File "C:\Python27\lib\distutils\msvc9compiler.py", line 473, in compile
        self.initialize()
      File "C:\Python27\lib\distutils\msvc9compiler.py", line 383, in initialize
        vc_env = query_vcvarsall(VERSION, plat_spec)
      File "C:\Python27\lib\site-packages\setuptools\msvc.py", line 173, in msvc9_query_vcvarsall
        return EnvironmentInfo(arch, ver).return_env()
      File "C:\Python27\lib\site-packages\setuptools\msvc.py", line 1103, in return_env
        [self.VCIncludes,
      File "C:\Python27\lib\site-packages\setuptools\msvc.py", line 811, in VCIncludes
        return [os.path.join(self.si.VCInstallDir, 'Include'),
      File "C:\Python27\lib\site-packages\setuptools\msvc.py", line 541, in VCInstallDir
        python_vc = self.ri.lookup(reg_path, 'installdir')
      File "C:\Python27\lib\site-packages\setuptools\msvc.py", line 451, in lookup
        bkey = winreg.OpenKey(hkey, key, 0, winreg.KEY_READ)
    WindowsError: [Error 2] The system cannot find the file specified

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\username\appdata\local\temp\pip-build-gsn2z7\pyproj\

setuptools are up to date.

**Comment by weapon-x** [comment]
Do you have the compiler for windows installed?

https://www.microsoft.com/en-us/download/details.aspx?id=44266

**Comment by dustin1525** [comment]
Add that to the readme

**Comment by abhirathod95** [comment]
I fixed this issue (and another compiler issue following this issue pertaining to markupspace) by downloading the wheel file from http://www.lfd.uci.edu/~gohlke/pythonlibs/#pyproj and then running pip install on those files. Fixed the issues for me.
