### ISSUE TITLE
Won't Start

### ISSUE THREAD

**Issue by blackpoc** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#82]
Won't start on my server with python 3 installed. Looking for a little help/direction to get it going:

```
$ python3 pokebot.py -i 0
Traceback (most recent call last):
  File "pokebot.py", line 15, in <module>
    from pgoapi import PGoApi
  File "/home/removed/pkmn/pkmn-bot2/pgoapi/__init__.py", line 18, in <module>
    from pgoapi.pgoapi import PGoApi
  File "/home/removed/pkmn/pkmn-bot2/pgoapi/pgoapi.py", line 7, in <module>
    from itertools import chain, imap
ImportError: cannot import name 'imap'
```

**Comment by TomTheBotter** [comment]
python 2.7 not 3

**Comment by blackpoc** [comment]
Thanks.
