### ISSUE TITLE
'Crypto.Cipher._raw_ecb'

### ISSUE THREAD

**Issue by mieburungdara** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#89]
```
[Traceback (most recent call last):
  File "pokebot.py", line 15, in <module>
    from pgoapi import PGoApi
  File "C:\Python27\Pokemon-Go-Bot-Working-Hack-API\pgoapi\__init__.py", line 18, in <module>
    from pgoapi.pgoapi import PGoApi
  File "C:\Python27\Pokemon-Go-Bot-Working-Hack-API\pgoapi\pgoapi.py", line 13, in <module>
    from pgoapi.auth_google import AuthGoogle
  File "C:\Python27\Pokemon-Go-Bot-Working-Hack-API\pgoapi\auth_google.py", line 28, in <module>
    from gpsoauth import perform_master_login, perform_oauth
  File "C:\Python27\lib\site-packages\gpsoauth\__init__.py", line 4, in <module>
    from . import google
  File "C:\Python27\lib\site-packages\gpsoauth\google.py", line 5, in <module>
    from PublicKey import RSA
  File "C:\Python27\Lib\Crypto\PublicKey\RSA.py", line 79, in <module>
    from Crypto.IO import PKCS8, PEM
  File "C:\Python27\Lib\Crypto\IO\PKCS8.py", line 73, in <module>
    from Crypto.IO._PBES import PBES1, PBES2, PbesError
  File "C:\Python27\Lib\Crypto\IO\_PBES.py", line 44, in <module>
    from Crypto.Cipher import DES, ARC2, DES3, AES
  File "C:\Python27\Lib\Crypto\Cipher\__init__.py", line 78, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "C:\Python27\Lib\Crypto\Cipher\_mode_ecb.py", line 46, in <module>
    """
  File "C:\Python27\Lib\Crypto\Util\_raw_api.py", line 168, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s'" % name)
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb']
```

**Comment by izanagi1995** [comment]
Did you have installed all requirements?

**Comment by mieburungdara** [comment]
i did, one by one with same version

**Comment by Sytharix** [comment]
Try installing the requirements by navigating to the directory and running `pip install -r requirements.txt`.
