### ISSUE TITLE
JSON Decoder

### ISSUE THREAD

**Issue by cnray3** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#9]
Traceback (most recent call last):
  File "pokebot.py", line 184, in <module>
    main()
  File "pokebot.py", line 113, in main
    config = init_config()
  File "pokebot.py", line 74, in init_config
    load.update(json.load(data))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

Attempted to marry latitude/longitude in config.json, did not solve. Looks like it could be an issue with the API?

**Comment by kairotox** [comment]
Same: Traceback (most recent call last):
  File "pokebot.py", line 194, in <module>
    main()
  File "pokebot.py", line 122, in main
    config = init_config()
  File "pokebot.py", line 83, in init_config
    load.update(json.load(data))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by TomTheBotter** [comment]
Edit the latitude and longitude in the pokebot.py file not in the config.json

**Comment by cnray3** [comment]
Okay. So pokebot.py has 43 whatever and 90 whatever and now json just has St. Paul, MN.

**Comment by cnray3** [comment]
SOLVED: editing the file in WebStorm worked; textedit on Mac effed up the formatting.
